Repository DPCMGroup/bc19-docs, pull requests merged in 2021-03, with the labels that each got.

#84 Feature/ver 2021 02 11
  interni/verbali/VI_2021_02_11/main.tex
  interni/verbali/VI_2021_02_11/res/configurazione.tex
  interni/verbali/VI_2021_02_11/res/contenuto.tex
  interni/verbali/VI_2021_02_11/res/frontespizio.tex
  interni/verbali/VI_2021_02_11/res/images/background.png
  interni/verbali/VI_2021_02_11/res/images/logo.png
  interni/verbali/VI_2021_02_11/res/registro.tex
  interni/verbali/VI_2021_02_11/res/tracciamenti.tex
Labels: verbale

#83 aggiornamento glossario
  esterni/glossario/main.tex
  esterni/glossario/res/registro.tex
  esterni/glossario/res/sections/dizionario.tex
Labels: documentation, glossario, verifica

#85 Feature/ver 2021 02 16
  interni/verbali/VI_2021_02_16/main.tex
  interni/verbali/VI_2021_02_16/res/configurazione.tex
  interni/verbali/VI_2021_02_16/res/contenuto.tex
  interni/verbali/VI_2021_02_16/res/frontespizio.tex
  interni/verbali/VI_2021_02_16/res/images/background.png
  interni/verbali/VI_2021_02_16/res/images/logo.png
  interni/verbali/VI_2021_02_16/res/registro.tex
  interni/verbali/VI_2021_02_16/res/tracciamenti.tex
Labels: verbale

#81 Merge Feature/correzioniAdR in develop
  esterni/AnalisiDeiRequisiti/main.tex
  esterni/AnalisiDeiRequisiti/res/images/UC10.png
  esterni/AnalisiDeiRequisiti/res/images/UC11.png
  esterni/AnalisiDeiRequisiti/res/images/UC12.png
  esterni/AnalisiDeiRequisiti/res/images/UC13.png
  esterni/AnalisiDeiRequisiti/res/images/UC14.png
  esterni/AnalisiDeiRequisiti/res/images/UC15.png
  esterni/AnalisiDeiRequisiti/res/images/UC19.png
  esterni/AnalisiDeiRequisiti/res/images/UC24.png
  esterni/AnalisiDeiRequisiti/res/images/UC26.png
  esterni/AnalisiDeiRequisiti/res/images/UC28.png
  esterni/AnalisiDeiRequisiti/res/images/UC6.png
  esterni/AnalisiDeiRequisiti/res/registro.tex
  esterni/AnalisiDeiRequisiti/res/sections/casiUso.tex
  esterni/AnalisiDeiRequisiti/res/sections/descrizioneGenerale.tex
  esterni/AnalisiDeiRequisiti/res/sections/introduzione.tex
  esterni/AnalisiDeiRequisiti/res/sections/requisiti.tex
Labels: AdR, documentation, verifica

#95 aggiunta sezione riguardante la pull request
  interni/NormeDiProgetto/main.tex
  interni/NormeDiProgetto/res/registro.tex
  interni/NormeDiProgetto/res/sections/processiSupporto.tex
Labels: NdP, verifica

#96 Feature/ver est 2021 02 22
  esterni/verbali/VE_2021_02_20/main.tex
  esterni/verbali/VE_2021_02_20/res/configurazione.tex
  esterni/verbali/VE_2021_02_20/res/contenuto.tex
  esterni/verbali/VE_2021_02_20/res/frontespizio.tex
  esterni/verbali/VE_2021_02_20/res/images/background.png
  esterni/verbali/VE_2021_02_20/res/images/logo.png
  esterni/verbali/VE_2021_02_20/res/registro.tex
  esterni/verbali/VE_2021_02_20/res/tracciamenti.tex
Labels: verbale, verifica

#101 Feature/ver 2021 02 28
  interni/verbali/VI_2021_02_28/main.tex
  interni/verbali/VI_2021_02_28/res/configurazione.tex
  interni/verbali/VI_2021_02_28/res/contenuto.tex
  interni/verbali/VI_2021_02_28/res/frontespizio.tex
  interni/verbali/VI_2021_02_28/res/images/background.png
  interni/verbali/VI_2021_02_28/res/images/logo.png
  interni/verbali/VI_2021_02_28/res/registro.tex
  interni/verbali/VI_2021_02_28/res/tracciamenti.tex
Labels: verbale, verifica

#102 Aggiornamento PdQ
  esterni/PianoDiQualifica/main.tex
  esterni/PianoDiQualifica/res/images/AC.png
  esterni/PianoDiQualifica/res/images/BAC.png
  esterni/PianoDiQualifica/res/images/CV.png
  esterni/PianoDiQualifica/res/images/EV.png
  esterni/PianoDiQualifica/res/images/IndiceGulpease.png
  esterni/PianoDiQualifica/res/images/PV.png
  esterni/PianoDiQualifica/res/images/SV.png
  esterni/PianoDiQualifica/res/registro.tex
  esterni/PianoDiQualifica/res/sections/QualitaDiProcesso.tex
  esterni/PianoDiQualifica/res/sections/ResocontoVerifica.tex
  esterni/PianoDiQualifica/res/sections/SpecificaTest.tex
Labels: PdQ, help wanted, verifica
